In [3]:
def convert_measurements():
    """
    Displays a menu of conversion options and prompts the user to select one.
    Supports conversions between metric and imperial units:
    - Length: meters <-> feet
    - Weight: kilograms <-> pounds
    - Volume: liters <-> gallons

    Raises:
        ValueError: If the user enters an invalid choice or non-numeric input.
    """
    conversions = {
        "m -> ft": lambda n: n * 3.280,
        "ft -> m": lambda n: n * 0.3048,
        "kg -> lbs": lambda n: n * 2.20462,
        "lbs -> kg": lambda n: n * 0.453592,
        "l -> gal": lambda n: n * 0.264172,
        "gal -> l": lambda n: n * 3.78541
    }

    for i, k in enumerate(conversions):
        print(f"{i}) {k}")

    try:
        operation = int(input("Enter your choice: "))
        num = float(input("Enter a number: "))

        if operation < 0 or operation >= len(conversions):
            raise ValueError("Invalid choice. Please select a valid option.")

        key = list(conversions.keys())[operation]
        result = conversions[key](num)
        print(f"{num} {key} = {result}")


    except ValueError as ve:
        print(f"Input Error: {ve}")

    except Exception as e:
        print(f"Error: {e}")

convert_measurements()


0) m -> ft
1) ft -> m
2) kg -> lbs
3) lbs -> kg
4) l -> gal
5) gal -> l
Enter your choice: 3
Enter a number: 23423423
23423423.0 lbs -> kg = 10624677.285416


In [4]:
def calculator():
    """
    Prompts the user to select an operation (sum, average, maximum, or minimum)
    and enter a list of numbers. Performs the selected operation and displays the result.

    Operations:
        1) Sum - Returns the sum of all numbers
        2) Average - Returns the arithmetic mean
        3) Maximum - Returns the largest number
        4) Minimum - Returns the smallest number

    Raises:
        ValueError: If the user enters an invalid choice or non-numeric input, or if an empty list is provided.
    """
    operations = {"1": ("Sum", sum), "2": ("Average", lambda n: sum(n)/len(n)),
                 "3": ("Maximum", max), "4": ("Minimum", min)}

    print("1) Sum\n2) Average\n3) Maximum\n4) Minimum")
    op = input("Choose operation: ")

    if op not in operations:
        print("Invalid choice.")
        return

    try:
        nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not nums: raise ValueError("Empty list")
        print(f"Result: {operations[op][1](nums)}")
    except ValueError as e:
        print(f"Error: {e}")

calculator()


1) Sum
2) Average
3) Maximum
4) Minimum
Choose operation: 2
Enter numbers separated by spaces: 3 1 2 3 5 
Result: 2.8


In [6]:
def extract_every_other(lst): return lst[::2]
def get_sublist(lst, start, end): return lst[start:end+1]
def reverse_list(lst): return lst[::-1]
def remove_first_last(lst): return lst[1:-1]
def get_first_n(lst, n): return lst[:n]
def get_last_n(lst, n): return lst[-n:]
def reverse_skip(lst): return lst[-2::-2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))
print(reverse_list([1, 2, 3, 4, 5]))
print(remove_first_last([1, 2, 3, 4, 5]))
print(get_first_n([1, 2, 3, 4, 5], 3))
print(get_last_n([1, 2, 3, 4, 5], 2))
print(reverse_skip([1, 2, 3, 4, 5, 6]))


[1, 3, 5]
[3, 4, 5]
[5, 4, 3, 2, 1]
[2, 3, 4]
[1, 2, 3]
[4, 5]
[5, 3, 1]


In [7]:
def flatten(lst):
    return [x for sub in lst for x in sub]


def access_nested_element(lst, indices):
    result = lst
    for index in indices:
        result = result[index]
    return result


def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val


def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


print(flatten([[1, 2], [3, 4], [5]]))
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print(sum_nested([[1, 2], [3, [4, 5]], 6]))
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))
print(find_max([[1, 2], [3, [4, 5]], 6]))
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print(average_nested([[1, 2], [3, 4], [5, 6]]))


[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


In [32]:
import numpy as np


# 1. Empty array 2X2
empty_arr = np.empty((2, 2))
print(f"Empty array (2x2): {empty_arr}")


Empty array (2x2): [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]


In [10]:

# 2. All one array 4X2
ones_arr = np.ones((4, 2))
print(f"All one array (4x2): {ones_arr}")


All one array (4x2): [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:


# 3. Array filled with fill value
full_arr = np.full((3, 3), 7)
print(f"Full array (filled with 7): {full_arr}")


Full array (filled with 7): [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
# 4. Zeros like another array
given = np.array([[1, 2], [3, 4]])
zeros_like_arr = np.zeros_like(given)
print(f"Zeros like given array: {zeros_like_arr}")



Zeros like given array: [[0 0]
 [0 0]]


In [13]:

# 5. Ones like another array
ones_like_arr = np.ones_like(given)
print(f"Ones like given array: {ones_like_arr}")


Ones like given array: [[1 1]
 [1 1]]


In [14]:


# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print(f"Converted from list: {numpy_arr}")


Converted from list: [1 2 3 4]


In [15]:


# ------------- Array Manipulation

# 1. Array from 10 to 49
arr_10_49 = np.arange(10, 50)
print(f"Array 10-49: {arr_10_49}n")



Array 10-49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]n


In [16]:

# 2. 3x3 matrix 0-8
matrix_0_8 = np.arange(9).reshape(3, 3)
print(f"3x3 matrix 0-8: {matrix_0_8}")


3x3 matrix 0-8: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:


# 3. 3x3 identity matrix
identity = np.eye(3)
print(f"3x3 identity matrix: {identity}")


3x3 identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 4. Random array of size 30, find mean
random_arr = np.random.random(30)
print(f"Random array mean: {random_arr.mean()}")


Random array mean: 0.42750063236065283


In [21]:
# 5. 10x10 random array, min and max
random_10x10 = np.random.random((10, 10))
print(f"Min: {random_10x10.min()}, Max: {random_10x10.max()}")


Min: 0.0021818661990716803, Max: 0.9957097446366002


In [22]:


# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(f"Zero array with 5th element=1: {zero_arr}")



Zero array with 5th element=1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:

# 7. Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Reversed array: {reversed_arr}")



Reversed array: [0 4 0 0 2 1]


In [24]:

# 8. 2d array with 1 on border, 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(f"Border array: {border_arr}")


Border array: [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# 9. 8x8 checkerboard pattern
checker = np.zeros((8, 8))
checker[::2, ::2] = 1
checker[1::2, 1::2] = 1
print(f"Checkerboard pattern: {checker}")


Checkerboard pattern: [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [26]:
# ----------- Array Operations

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(f"x = {x} y = {y} v = {v} w = {w}")


x = [[1 2]
 [3 5]] y = [[5 6]
 [7 8]] v = [ 9 10] w = [11 12]


In [27]:
# 1. Add arrays
print(f"x + y = {x + y}")

# 2. Subtract arrays
print(f"x - y = {x - y}")

# 3. Multiply by integer
print(f"x * 3 = {x * 3}")

# 4. Square of each element
print(f"x ** 2 ={x ** 2}")

# 5. Dot products
print(f"v . w = {np.dot(v, w)}")
print(f"x . v = {np.dot(x, v)}")
print(f"x . y ={np.dot(x, y)}")

# 6. Concatenate
print(f"Concatenate x and y (rows): {np.concatenate((x, y), axis=0)}")
print(f"Concatenate v and w (columns): {np.column_stack((v, w))}")

# 7. Concatenate x and v (error explanation)
try:
    np.concatenate((x, v))
except Exception as e:
    print(f"Error concatenating x and v: {e}")



x + y = [[ 6  8]
 [10 13]]
x - y = [[-4 -4]
 [-4 -3]]
x * 3 = [[ 3  6]
 [ 9 15]]
x ** 2 =[[ 1  4]
 [ 9 25]]
v . w = 219
x . v = [29 77]
x . y =[[19 22]
 [50 58]]
Concatenate x and y (rows): [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w (columns): [[ 9 11]
 [10 12]]
Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [28]:
# ------- Matrix Ops

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print(f"A = {A}; B = {B}")

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
print(f"A * A^-1 = I: {np.dot(A, A_inv)}")



A = [[3 4]
 [7 8]]; B = [[5 3]
 [2 1]]
A * A^-1 = I: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [29]:

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"AB ={AB}\nBA ={BA}\nAB != BA: {not np.array_equal(AB, BA)}")



AB =[[23 13]
 [51 29]]
BA =[[36 44]
 [13 16]]
AB != BA: True


In [30]:

# 3. Prove (AB)^T = B^T * A^T
AB_T = AB.T
B_T_A_T = np.dot(B.T, A.T)
print(f"(AB)^T ={AB_T}\nB^T * A^T ={B_T_A_T}\n(AB)^T = B^T * A^T: {np.array_equal(AB_T, B_T_A_T)}")


(AB)^T =[[23 51]
 [13 29]]
B^T * A^T =[[23 51]
 [13 29]]
(AB)^T = B^T * A^T: True


In [31]:

# Solve system of linear equations using inverse
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

coeffs = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])

# Using inverse method
coeffs_inv = np.linalg.inv(coeffs)
solution = np.dot(coeffs_inv, constants)
print(f"Solution using inverse (x, y, z): {solution}")

# Using np.linalg.solve
solution_solve = np.linalg.solve(coeffs, constants)
print(f"Solution using solve (x, y, z): {solution_solve}")

# Verify the solution
print("Verification:")
print(f"2({solution[0]}) - 3({solution[1]}) + {solution[2]} = {2*solution[0] - 3*solution[1] + solution[2]}")
print(f"{solution[0]} - {solution[1]} + 2({solution[2]}) = {solution[0] - solution[1] + 2*solution[2]}")
print(f"3({solution[0]}) + {solution[1]} - {solution[2]} = {3*solution[0] + solution[1] - solution[2]}")

Solution using inverse (x, y, z): [ 2.  1. -2.]
Solution using solve (x, y, z): [ 2.  1. -2.]
Verification:
2(2.0) - 3(1.0) + -2.0 = -1.0
2.0 - 1.0 + 2(-2.0) = -3.0
3(2.0) + 1.0 - -2.0 = 9.0


In [33]:
import time
import random
import numpy as np

SIZE = 1_000_000
MAT  = 1000

def timer(label, fn):
    start  = time.time()
    result = fn()
    end    = time.time()
    print(f"  {label:<30} {(end - start)*1000:.4f} ms")
    return result

py_a  = [random.random() for _ in range(SIZE)]
py_b  = [random.random() for _ in range(SIZE)]
np_a  = np.array(py_a)
np_b  = np.array(py_b)

py_m1 = [[random.random() for _ in range(MAT)] for _ in range(MAT)]
py_m2 = [[random.random() for _ in range(MAT)] for _ in range(MAT)]
np_m1 = np.array(py_m1)
np_m2 = np.array(py_m2)

# Element Wise Add
print("1. Element-wise Addition (size 1,000,000)")
timer("Python list",  lambda: [a + b for a, b in zip(py_a, py_b)])
timer("NumPy array",  lambda: np_a + np_b)

# Element Wise Mul
print("2. Element-wise Multiplication (size 1,000,000)")
timer("Python list",  lambda: [a * b for a, b in zip(py_a, py_b)])
timer("NumPy array",  lambda: np_a * np_b)

# Dot Product
print("3. Dot Product (size 1,000,000)")
timer("Python list",  lambda: sum(a * b for a, b in zip(py_a, py_b)))
timer("NumPy array",  lambda: np.dot(np_a, np_b))

# Matrix Multiplication
print("4. Matrix Multiplication (1000 x 1000)")
def py_matmul(A, B):
    n = len(A)
    C = [[0.0] * n for _ in range(n)]
    for i in range(n):
        for k in range(n):
            if A[i][k] == 0:
                continue
            for j in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

timer("Python list",  lambda: py_matmul(py_m1, py_m2))
timer("NumPy array",  lambda: np_m1 @ np_m2)

1. Element-wise Addition (size 1,000,000)
  Python list                    75.8698 ms
  NumPy array                    4.0989 ms
2. Element-wise Multiplication (size 1,000,000)
  Python list                    59.7401 ms
  NumPy array                    2.5773 ms
3. Dot Product (size 1,000,000)
  Python list                    67.2050 ms
  NumPy array                    1.4241 ms
4. Matrix Multiplication (1000 x 1000)
  Python list                    108986.7711 ms
  NumPy array                    58.4090 ms


array([[248.41354013, 257.51759579, 252.73415443, ..., 251.22828762,
        248.19849501, 247.85047517],
       [244.02302257, 252.55309168, 248.44192676, ..., 245.90116679,
        246.53528278, 245.68427699],
       [249.45995735, 253.41159868, 251.59668811, ..., 238.9735616 ,
        241.9744867 , 242.6546252 ],
       ...,
       [247.43058301, 253.31716966, 248.57757713, ..., 241.92803161,
        244.18036446, 243.71404217],
       [241.79131323, 251.54820816, 251.14875884, ..., 241.41160045,
        241.19752429, 248.67845752],
       [254.81074302, 263.24777768, 256.69652542, ..., 253.77075173,
        254.0680978 , 251.20478225]])